### PR TITLE
Added Floating Point company to the list

### PR DESCRIPTION
**Pull request by dlatin**
Added Floating Point company to the list. Authors of Keechma framework.

### CODE REVIEW

**Comment by swannodette** [comment]
@dlatin would love to add this, have you submitted your CA?

**Comment by dlatin** [comment]
Sorry, haven't noticed your message sooner! Yes, I have submitted my CA. Back when I added Floating Point to the list.

**Comment by swannodette** [comment]
@dlatin thanks!

**Comment by dlatin** [comment]
@swannodette thank you :)

**Pull request merged**
