### PR TITLE
State where files included in :preamble should live.

### PR DESCRIPTION
**Pull request by jszakmeister**

### CODE REVIEW

**Comment by Deraen** [comment]
"Resources directory" is feature of build tools, not something ClojureScript knows about.

ClojureScript compiler reads the preamble files from classpath, where built tools place resource paths.

So, I think it would be best instead say that the files should be present in the classpath.

**Comment by jszakmeister** [comment]
Sure, I'll update the pull request.

**Comment by swannodette** [comment]
@jszakmeister have you submitted your CA?

**Comment by jszakmeister** [comment]
Yes sir, I submitted it a number of years ago and I'm on the list. :-)

**Pull request merged**
