### PR TITLE
Correct namespace spelling in javascript-modules

### PR DESCRIPTION
**Pull request by arsenerei**

### CODE REVIEW

**Comment by swannodette** [comment]
@arsenerei thanks for the pull request. Please submit your CA so that we can merge this change. https://clojure.org/community/contributing

**Comment by arsenerei** [comment]
@swannodette Done. :)

**Comment by swannodette** [comment]
This is not a spelling error. It supposed to be CJS for CommonJS

**Comment by arsenerei** [comment]
Ah, my mistake.

**Pull request closed without merging**
